name: Policy Test

on:
  push:
    branches:
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          path: policies

      - name: Clone Kyverno
        run: |
          if [[ ${{ github.event_name }} == "push" ]]
          then
            GIT_BRANCH=${GITHUB_REF##*/}
          elif [[ ${{ github.event_name }} == "pull_request" ]]
          then
            GIT_BRANCH=${{ github.event.pull_request.base.ref }}
          fi

          git clone https://github.com/kyverno/kyverno --branch $GIT_BRANCH

      - name: Set up Go 
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: 1.17

      - name: Test Policy
        run: |
          cd kyverno
          go run cmd/cli/kubectl-kyverno/main.go test ../policies
