name: Policy Test

on:
  push:
    branches:
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2.4.0
        with:
          path: policies

      - name: Clone Kyverno
        run: |
          if [[ ${{ github.event_name }} == "push" ]]
          then
            GIT_BRANCH=${GITHUB_REF##*/}
          elif [[ ${{ github.event_name }} == "pull_request" ]]
          then
            GIT_BRANCH=${{ github.event.pull_request.base.ref }}
          fi

          git clone https://github.com/kyverno/kyverno --branch $GIT_BRANCH

      - name: Set up Go 
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: 1.17

      - name: Test Policy
        run: |
          cd kyverno
          go run cmd/cli/kubectl-kyverno/main.go test ../policies